// <auto-generated />
namespace kimyatesti.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ogrTestTakip_ICollections_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ogrTestTakip_ICollections_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202006201136570_ogrTestTakip_ICollections_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
