// <auto-generated />
namespace kimyatesti.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AvatarTestGroupConnectionRevised2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AvatarTestGroupConnectionRevised2));
        
        string IMigrationMetadata.Id
        {
            get { return "202006181650214_Avatar-TestGroup-Connection-Revised2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
